routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'IndexController@index')->name('index');
    Route::get('/getData', 'IndexController@getData')->name('index.data');

    Route::resource('task', 'TaskController');
    Route::post('/task/sort', 'TaskController@postSort')->name('task.sort');
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Task
 * @package App
 */
class Task extends Model
{
    use SoftDeletes;
    /**
     * @var array
     */
    protected $fillable = ['name', 'priority', 'project_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function project()
    {
        return $this->belongsTo('App\Project', 'project_id');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Helper;
use App\Project;
use App\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $projects = Project::select('id', 'name')->get();

        return view('task.create', ['projects' => $projects]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->isMethod('post')) {
            $validatedData = $request->validate([
                'taskName' => 'required|max:255',
                'priority' => 'required|integer',
                'project' => 'integer',
            ]);

            $newTask = new Task;
            $newTask->name = $request->post('taskName');
            $newTask->priority = intval($request->post('priority'));

            if (intval($request->post('project')) > 0) {
                $newTask->project_id = intval($request->post('project'));
            }

            $saved = $newTask->save();

            if (!$saved) {
                return redirect()->back()->withErrors('Unable to save.');
            }
        }

        Helper::reorderTasks();

        return redirect()->route('index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find(intval($id));
        $projects = Project::select('id', 'name')->get();

        return view('task.edit', ['task' => $task, 'projects' => $projects]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'taskName' => 'required|max:255',
            'priority' => 'required|integer',
            'project' => 'integer',
        ]);

        //if(!$request->isMethod('PUT') || !$request->isMethod('PATCH'))
        if (!$request->isMethod('PUT')) {
            return response()->json(array('status' => 'error', 'message' => 'Wrong method.'));
        }

        $task = Task::find(intval($id));
        if (!$task) {
            return response()->json(array('status' => 'error', 'message' => 'Task not found.'));
        }
        // taskName=Task1&priority=3&project=0

        $task->name = $request->post('taskName');
        $task->priority = intval($request->post('priority'));
        $task->project_id = intval($request->post('project')) === 0 ? null : intval($request->post('project'));

        $saved = $task->save();

        if (!$saved) {
            return redirect()->back()->withErrors('Unable to save.');
        }

        Helper::reorderTasks();

        return redirect()->route('index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if (!$request->ajax()) {
            return response()->json(array('status' => 'error', 'message' => 'Unable to delete task.'));
        }

        if (!$request->isMethod('delete')) {
            return response()->json(array('status' => 'error', 'message' => 'Unable to delete task.'));
        }

        $task = Task::find(intval($id));
        if (!$task) {
            return response()->json(array('status' => 'error', 'message' => 'Task not found.'));
        }

        $deleted = $task->delete();
        if (!$deleted) {
            return response()->json(array('status' => 'error', 'message' => 'Unable to delete task.'));
        }

        return response()->json(array('status' => 'success', 'message' => 'Task deleted.'));
    }

    /**
     * @param  Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function postSort(Request $request)
    {
        if ($request->ajax()) {
            if ($request->isMethod('post')) {
                $items = $request->post('data');

                if (!is_array($items)) {
                    return response()->json(['status' => 'error', 'message' => 'Error no#1.']);
                }

                foreach ($items as $item => $value) {
                    $task = Task::find(intval($value["id"]));

                    if (!$task) {
                        return response()->json(['status' => 'error', 'message' => 'Task not found.']);
                    }

                    $task->priority = intval($value["priority"]);
                    $saved = $task->save();

                    if (!$saved) {
                        return response()->json(['status' => 'error', 'message' => 'Unable to save.']);
                    }
                }
                Helper::reorderTasks();
                return response()->json(['status' => 'success', 'message' => 'Updated.']);
            }
        }
    }
}

resources/views/task/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form method="POST" action="{{ route('task.store') }}">
                            @csrf
                            <div class="form-group">
                                <label for="taskName">Task Name</label>
                                <input type="text" class="form-control" id="taskName" name="taskName"
                                       aria-describedby="taskNameHelp">
                                <small id="taskNameHelp" class="form-text text-muted">Name of task.</small>
                            </div>
                            <div class="form-group">
                                <label for="priority">Priority</label>
                                <input type="text" class="form-control" id="priority" name="priority"
                                       aria-describedby="priorityHelp">
                                <small id="priorityHelp" class="form-text text-muted">Priority.</small>
                            </div>
                            <div class="form-group">
                                <label for="project">Project</label>
                                <select class="form-control" id="project" name="project">
                                    <option value="0">None</option>
                                    @if(count($projects) > 0)
                                        @foreach($projects as $project)
                                            <option value="{{ $project->id }}">{{ $project->name }}</option>
                                        @endforeach
                                    @endif
                                </select>
                                <small id="projectHelp" class="form-text text-muted">Project.</small>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/task/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form method="POST" action="{{ route('task.update', $task->id) }}">
                            <input type="hidden" name="_method" value="PUT"/>
                            @csrf
                            <div class="form-group">
                                <label for="taskName">Task Name</label>
                                <input type="text" value="{{ $task->name }}" class="form-control" id="taskName"
                                       name="taskName" aria-describedby="taskNameHelp">
                                <small id="taskNameHelp" class="form-text text-muted">Name of task.</small>
                            </div>
                            <div class="form-group">
                                <label for="priority">Priority</label>
                                <input type="text" value="{{ $task->priority }}" class="form-control" id="priority"
                                       name="priority" aria-describedby="priorityHelp">
                                <small id="priorityHelp" class="form-text text-muted">Priority.</small>
                            </div>
                            <div class="form-group">
                                <label for="project">Project</label>
                                <select class="form-control" id="project" name="project">
                                    <option value="0">None</option>
                                    @if(count($projects) > 0)
                                        @foreach($projects as $project)
                                            <option value='{{ $project->id }}' {{ $task->project_id === $project->id ? "selected" : ""  }}>{{ $project->name }}</option>
                                        @endforeach
                                    @endif
                                </select>
                                <small id="projectHelp" class="form-text text-muted">Project.</small>
                            </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection